String.toLocaleString({

	"it": {
    "%game-intro"           : "Join the <strong>AFL!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a target=\"_blank\">DevKezz</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-AFL #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'Adelaide Crows',
    '%4'                    : 'Gold Coast Suns',
    '%8'                    : 'Calton',
    '%16'                   : 'Hawthorn',
    '%32'                   : 'Western Bulldogs',
    '%64'                   : 'GWS Giants',
    '%128'                  : 'Saints',
	'%256'                  : 'Collingwood',
    '%512'                  : 'Richmond',
    '%1024'                 : 'West Coast Eagles',
    '%2048'                 : 'Brisbane Lions',
    '%4096'                 : 'Port Adelaide',
    '%8192'                 : 'Geelong',
    '%p0'                   : 'Adelaide Crows',
    '%p4'                   : 'Gold Coast Suns',
    '%p8'                   : 'Calton',
    '%p16'                  : 'Hawthorn',
    '%p32'                  : 'Western Bulldogs',
    '%p64'                  : 'GWS Giants',
    '%p128'                 : 'Saints',
    '%p256'                 : 'Collingwood',
    '%p512'                 : 'Richmond',
    '%p1024'                : 'West Coast Eagles',
    '%p2048'                : 'Brisbane Lions',
    '%p4096'                : 'Port Adelaide',
    '%p8192'                : 'Geelong'

	},

  "en": {
    "%game-intro"           : "Join the <strong>AFL!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a target=\"_blank\">DevKezz</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-AFL #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'Adelaide Crows',
    '%4'                    : 'Gold Coast Suns',
    '%8'                    : 'Calton',
    '%16'                   : 'Hawthorn',
    '%32'                   : 'Western Bulldogs',
    '%64'                   : 'GSW Giants',
    '%128'                  : 'Saints',
    '%256'                  : 'Collingwood',
    '%512'                  : 'Richmond',
    '%1024'                 : 'West Coast Eagles',
    '%2048'                 : 'Brisbane Lions',
    '%4096'                 : 'Port Adelaide',
    '%8192'                 : 'Geelong',
    '%p0'                   : 'Adelaide Crows',
    '%p4'                   : 'Gold Coast Suns',
    '%p8'                   : 'Calton',
    '%p16'                  : 'Hawthorn',
    '%p32'                  : 'Western Bulldogs',
    '%p64'                  : 'GWS Giants',
    '%p128'                 : 'Saints',
    '%p256'                 : 'Collingwood',
    '%p512'                 : 'Richmond',
    '%p1024'                : 'West Coast Eagles',
    '%p2048'                : 'Brisbane Lions',
    '%p4096'                : 'Port Adelaide',
    '%p8192'                : 'Geelong'
  }

});
